#!/bin/sh

echo "BleemQuark - Commodore 64 MINI prototype hack by Swingflip"
echo "-----------------------------------------------------------------------------------------------------------------------------------------------------"
echo " ModMyClassic.com / https://discordapp.com/invite/8gygsrw (This app is 100% free and always remain free)                                             "
echo "-----------------------------------------------------------------------------------------------------------------------------------------------------"